# General Jekyll Config

# if you don't need baseurl, you should leave this value blank.
baseurl: /monthly

highlighter: rouge
url: 'muygalan.github.io' # your host
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]